/* tslint:disable */
/* eslint-disable */
/**
 * My API
 * Auto-generated OpenAPI spec
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface CreateIngredientDto
 */
export interface CreateIngredientDto {
    /**
     * 
     * @type {string}
     * @memberof CreateIngredientDto
     */
    'name': string;
}
/**
 * 
 * @export
 * @interface CreateRecipeDto
 */
export interface CreateRecipeDto {
    /**
     * 
     * @type {string}
     * @memberof CreateRecipeDto
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof CreateRecipeDto
     */
    'content': string;
    /**
     * 
     * @type {string}
     * @memberof CreateRecipeDto
     */
    'img_url'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateRecipeDto
     */
    'ingredientIds': Array<string>;
}
/**
 * 
 * @export
 * @interface IngredientResponseDto
 */
export interface IngredientResponseDto {
    /**
     * 
     * @type {string}
     * @memberof IngredientResponseDto
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof IngredientResponseDto
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof IngredientResponseDto
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof IngredientResponseDto
     */
    'updatedAt': string;
}
/**
 * 
 * @export
 * @interface RecipeResponseDto
 */
export interface RecipeResponseDto {
    /**
     * 
     * @type {string}
     * @memberof RecipeResponseDto
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof RecipeResponseDto
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof RecipeResponseDto
     */
    'content': string;
    /**
     * 
     * @type {string}
     * @memberof RecipeResponseDto
     */
    'img_url': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof RecipeResponseDto
     */
    'ingredientIds': Array<string>;
    /**
     * 
     * @type {string}
     * @memberof RecipeResponseDto
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof RecipeResponseDto
     */
    'updatedAt': string;
}
/**
 * 
 * @export
 * @interface UpdateIngredientDto
 */
export interface UpdateIngredientDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateIngredientDto
     */
    'name'?: string;
}
/**
 * 
 * @export
 * @interface UpdateRecipeDto
 */
export interface UpdateRecipeDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateRecipeDto
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateRecipeDto
     */
    'content'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateRecipeDto
     */
    'img_url'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateRecipeDto
     */
    'ingredientIds'?: Array<string>;
}

/**
 * AppApi - axios parameter creator
 * @export
 */
export const AppApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        appControllerGetHealthcheck: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/healthcheck`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AppApi - functional programming interface
 * @export
 */
export const AppApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AppApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async appControllerGetHealthcheck(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.appControllerGetHealthcheck(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AppApi.appControllerGetHealthcheck']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AppApi - factory interface
 * @export
 */
export const AppApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AppApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        appControllerGetHealthcheck(options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.appControllerGetHealthcheck(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AppApi - object-oriented interface
 * @export
 * @class AppApi
 * @extends {BaseAPI}
 */
export class AppApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppApi
     */
    public appControllerGetHealthcheck(options?: RawAxiosRequestConfig) {
        return AppApiFp(this.configuration).appControllerGetHealthcheck(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * IngredientsApi - axios parameter creator
 * @export
 */
export const IngredientsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create ingredient
         * @param {CreateIngredientDto} createIngredientDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ingredientControllerCreateIngredient: async (createIngredientDto: CreateIngredientDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createIngredientDto' is not null or undefined
            assertParamExists('ingredientControllerCreateIngredient', 'createIngredientDto', createIngredientDto)
            const localVarPath = `/ingredient`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createIngredientDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get ingredients
         * @param {string} name 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ingredientControllerGetIngredients: async (name: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'name' is not null or undefined
            assertParamExists('ingredientControllerGetIngredients', 'name', name)
            const localVarPath = `/ingredient`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (name !== undefined) {
                localVarQueryParameter['name'] = name;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete ingredient
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ingredientControllerRemoveIngredient: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('ingredientControllerRemoveIngredient', 'id', id)
            const localVarPath = `/ingredient/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Edit ingredient
         * @param {string} id 
         * @param {UpdateIngredientDto} updateIngredientDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ingredientControllerUpdateIngredient: async (id: string, updateIngredientDto: UpdateIngredientDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('ingredientControllerUpdateIngredient', 'id', id)
            // verify required parameter 'updateIngredientDto' is not null or undefined
            assertParamExists('ingredientControllerUpdateIngredient', 'updateIngredientDto', updateIngredientDto)
            const localVarPath = `/ingredient/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateIngredientDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * IngredientsApi - functional programming interface
 * @export
 */
export const IngredientsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = IngredientsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create ingredient
         * @param {CreateIngredientDto} createIngredientDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async ingredientControllerCreateIngredient(createIngredientDto: CreateIngredientDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<IngredientResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.ingredientControllerCreateIngredient(createIngredientDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IngredientsApi.ingredientControllerCreateIngredient']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get ingredients
         * @param {string} name 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async ingredientControllerGetIngredients(name: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<IngredientResponseDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.ingredientControllerGetIngredients(name, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IngredientsApi.ingredientControllerGetIngredients']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete ingredient
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async ingredientControllerRemoveIngredient(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.ingredientControllerRemoveIngredient(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IngredientsApi.ingredientControllerRemoveIngredient']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Edit ingredient
         * @param {string} id 
         * @param {UpdateIngredientDto} updateIngredientDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async ingredientControllerUpdateIngredient(id: string, updateIngredientDto: UpdateIngredientDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.ingredientControllerUpdateIngredient(id, updateIngredientDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IngredientsApi.ingredientControllerUpdateIngredient']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * IngredientsApi - factory interface
 * @export
 */
export const IngredientsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = IngredientsApiFp(configuration)
    return {
        /**
         * 
         * @summary Create ingredient
         * @param {CreateIngredientDto} createIngredientDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ingredientControllerCreateIngredient(createIngredientDto: CreateIngredientDto, options?: RawAxiosRequestConfig): AxiosPromise<IngredientResponseDto> {
            return localVarFp.ingredientControllerCreateIngredient(createIngredientDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get ingredients
         * @param {string} name 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ingredientControllerGetIngredients(name: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<IngredientResponseDto>> {
            return localVarFp.ingredientControllerGetIngredients(name, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete ingredient
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ingredientControllerRemoveIngredient(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.ingredientControllerRemoveIngredient(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Edit ingredient
         * @param {string} id 
         * @param {UpdateIngredientDto} updateIngredientDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ingredientControllerUpdateIngredient(id: string, updateIngredientDto: UpdateIngredientDto, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.ingredientControllerUpdateIngredient(id, updateIngredientDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * IngredientsApi - object-oriented interface
 * @export
 * @class IngredientsApi
 * @extends {BaseAPI}
 */
export class IngredientsApi extends BaseAPI {
    /**
     * 
     * @summary Create ingredient
     * @param {CreateIngredientDto} createIngredientDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IngredientsApi
     */
    public ingredientControllerCreateIngredient(createIngredientDto: CreateIngredientDto, options?: RawAxiosRequestConfig) {
        return IngredientsApiFp(this.configuration).ingredientControllerCreateIngredient(createIngredientDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get ingredients
     * @param {string} name 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IngredientsApi
     */
    public ingredientControllerGetIngredients(name: string, options?: RawAxiosRequestConfig) {
        return IngredientsApiFp(this.configuration).ingredientControllerGetIngredients(name, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete ingredient
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IngredientsApi
     */
    public ingredientControllerRemoveIngredient(id: string, options?: RawAxiosRequestConfig) {
        return IngredientsApiFp(this.configuration).ingredientControllerRemoveIngredient(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Edit ingredient
     * @param {string} id 
     * @param {UpdateIngredientDto} updateIngredientDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IngredientsApi
     */
    public ingredientControllerUpdateIngredient(id: string, updateIngredientDto: UpdateIngredientDto, options?: RawAxiosRequestConfig) {
        return IngredientsApiFp(this.configuration).ingredientControllerUpdateIngredient(id, updateIngredientDto, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * RecipesApi - axios parameter creator
 * @export
 */
export const RecipesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create recipe
         * @param {CreateRecipeDto} createRecipeDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recipeControllerCreateRecipe: async (createRecipeDto: CreateRecipeDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createRecipeDto' is not null or undefined
            assertParamExists('recipeControllerCreateRecipe', 'createRecipeDto', createRecipeDto)
            const localVarPath = `/recipe`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createRecipeDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get recipe by Id
         * @param {string} id 
         * @param {any} id2 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recipeControllerGetRecipeDetails: async (id: string, id2: any, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('recipeControllerGetRecipeDetails', 'id', id)
            // verify required parameter 'id2' is not null or undefined
            assertParamExists('recipeControllerGetRecipeDetails', 'id2', id2)
            const localVarPath = `/recipe/{id}`
                .replace(`{${":id"}}`, encodeURIComponent(String(id)))
                .replace(`{${"id"}}`, encodeURIComponent(String(id2)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get recipes
         * @param {string} name 
         * @param {any} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recipeControllerGetRecipes: async (name: string, id: any, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'name' is not null or undefined
            assertParamExists('recipeControllerGetRecipes', 'name', name)
            // verify required parameter 'id' is not null or undefined
            assertParamExists('recipeControllerGetRecipes', 'id', id)
            const localVarPath = `/recipe`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (name !== undefined) {
                localVarQueryParameter['name'] = name;
            }

            if (id !== undefined) {
                for (const [key, value] of Object.entries(id)) {
                    localVarQueryParameter[key] = value;
                }
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete recipe
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recipeControllerRemoveRecipe: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('recipeControllerRemoveRecipe', 'id', id)
            const localVarPath = `/recipe/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Edit recipe
         * @param {string} id 
         * @param {UpdateRecipeDto} updateRecipeDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recipeControllerUpdateRecipe: async (id: string, updateRecipeDto: UpdateRecipeDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('recipeControllerUpdateRecipe', 'id', id)
            // verify required parameter 'updateRecipeDto' is not null or undefined
            assertParamExists('recipeControllerUpdateRecipe', 'updateRecipeDto', updateRecipeDto)
            const localVarPath = `/recipe/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateRecipeDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RecipesApi - functional programming interface
 * @export
 */
export const RecipesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RecipesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create recipe
         * @param {CreateRecipeDto} createRecipeDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async recipeControllerCreateRecipe(createRecipeDto: CreateRecipeDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RecipeResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.recipeControllerCreateRecipe(createRecipeDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RecipesApi.recipeControllerCreateRecipe']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get recipe by Id
         * @param {string} id 
         * @param {any} id2 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async recipeControllerGetRecipeDetails(id: string, id2: any, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RecipeResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.recipeControllerGetRecipeDetails(id, id2, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RecipesApi.recipeControllerGetRecipeDetails']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get recipes
         * @param {string} name 
         * @param {any} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async recipeControllerGetRecipes(name: string, id: any, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<RecipeResponseDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.recipeControllerGetRecipes(name, id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RecipesApi.recipeControllerGetRecipes']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete recipe
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async recipeControllerRemoveRecipe(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.recipeControllerRemoveRecipe(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RecipesApi.recipeControllerRemoveRecipe']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Edit recipe
         * @param {string} id 
         * @param {UpdateRecipeDto} updateRecipeDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async recipeControllerUpdateRecipe(id: string, updateRecipeDto: UpdateRecipeDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.recipeControllerUpdateRecipe(id, updateRecipeDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RecipesApi.recipeControllerUpdateRecipe']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * RecipesApi - factory interface
 * @export
 */
export const RecipesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RecipesApiFp(configuration)
    return {
        /**
         * 
         * @summary Create recipe
         * @param {CreateRecipeDto} createRecipeDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recipeControllerCreateRecipe(createRecipeDto: CreateRecipeDto, options?: RawAxiosRequestConfig): AxiosPromise<RecipeResponseDto> {
            return localVarFp.recipeControllerCreateRecipe(createRecipeDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get recipe by Id
         * @param {string} id 
         * @param {any} id2 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recipeControllerGetRecipeDetails(id: string, id2: any, options?: RawAxiosRequestConfig): AxiosPromise<RecipeResponseDto> {
            return localVarFp.recipeControllerGetRecipeDetails(id, id2, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get recipes
         * @param {string} name 
         * @param {any} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recipeControllerGetRecipes(name: string, id: any, options?: RawAxiosRequestConfig): AxiosPromise<Array<RecipeResponseDto>> {
            return localVarFp.recipeControllerGetRecipes(name, id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete recipe
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recipeControllerRemoveRecipe(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.recipeControllerRemoveRecipe(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Edit recipe
         * @param {string} id 
         * @param {UpdateRecipeDto} updateRecipeDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recipeControllerUpdateRecipe(id: string, updateRecipeDto: UpdateRecipeDto, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.recipeControllerUpdateRecipe(id, updateRecipeDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RecipesApi - object-oriented interface
 * @export
 * @class RecipesApi
 * @extends {BaseAPI}
 */
export class RecipesApi extends BaseAPI {
    /**
     * 
     * @summary Create recipe
     * @param {CreateRecipeDto} createRecipeDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecipesApi
     */
    public recipeControllerCreateRecipe(createRecipeDto: CreateRecipeDto, options?: RawAxiosRequestConfig) {
        return RecipesApiFp(this.configuration).recipeControllerCreateRecipe(createRecipeDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get recipe by Id
     * @param {string} id 
     * @param {any} id2 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecipesApi
     */
    public recipeControllerGetRecipeDetails(id: string, id2: any, options?: RawAxiosRequestConfig) {
        return RecipesApiFp(this.configuration).recipeControllerGetRecipeDetails(id, id2, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get recipes
     * @param {string} name 
     * @param {any} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecipesApi
     */
    public recipeControllerGetRecipes(name: string, id: any, options?: RawAxiosRequestConfig) {
        return RecipesApiFp(this.configuration).recipeControllerGetRecipes(name, id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete recipe
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecipesApi
     */
    public recipeControllerRemoveRecipe(id: string, options?: RawAxiosRequestConfig) {
        return RecipesApiFp(this.configuration).recipeControllerRemoveRecipe(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Edit recipe
     * @param {string} id 
     * @param {UpdateRecipeDto} updateRecipeDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecipesApi
     */
    public recipeControllerUpdateRecipe(id: string, updateRecipeDto: UpdateRecipeDto, options?: RawAxiosRequestConfig) {
        return RecipesApiFp(this.configuration).recipeControllerUpdateRecipe(id, updateRecipeDto, options).then((request) => request(this.axios, this.basePath));
    }
}



